application: scc-notifications-server
version: 4
runtime: php
api_version: 1

handlers:
- url: /sccnmevents
  script: sccnmevents.php

- url: /sccfbevents
  script: sccfbevents.php

- url: /sccslnm
  script: sccslnm.php

- url: /sccslfb
  script: sccslfb.php

- url: /sccac
  script: sccac.php
